### ISSUE TITLE
Práctica 9_Proyecto y Seguimiento

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-entrevista_gestion-de-proyecto#1]
[Practica 3  proyecto y seguimiento.pdf](https://github.com/user-attachments/files/17547748/Practica.3.proyecto.y.seguimiento.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by josealfredo79** [comment]
Bien hecho y revisado..Calificacio 19
